
-   name:       Dejar nginx listo!
    include_tasks:  |
                        tasks/distribuciones/{{ ansible_distribution }}/nginx.yaml
    tags:     
              - instalacion
              - configuracion

-   name:       Asegurar que la carpeta para la web está creada 
    file:
        path:   "{{ web.carpeta }}"
        state:  directory
    tags:
              - despliegue

-   name:       Asegurar que la última versión del repo está descargada en la carpeta
    git:
        repo:   '{{ web.repo }}'
        dest:   "{{ web.carpeta }}"
    notify:     REINICIO_REQUERIDO
    tags:
              - despliegue

-   name:       Asegurar que el servidor web queda arrancado
    service:
        name:   nginx
        state:  started
    register:   arranque
    tags:
              - despliegue
