
-   name:       Asegurar que NGINX queda instalado en el entorno
    apt:
        name:   "nginx={{nginx.version}}"
        state:  present
    tags:     
              - instalacion
              
-   name:       Asegurar que NGINX queda configurado como necesito para mi web
    template:
        src:    templates/configuracion.nginx.conf
        dest:   /etc/nginx/sites-available/default
        mode:   '0644'
    notify:     REINICIO_REQUERIDO
    tags:     
              - configuracion

-   name:       Asegurar que la carpeta para la web está creada 
    file:
        path:   "{{ web.carpeta }}"
        state:  directory
    tags:
              - despliegue

-   name:       Asegurar que la última versión del repo está descargada en la carpeta
    git:
        repo:   '{{ web.repo }}'
        dest:   "{{ web.carpeta }}"
    notify:     REINICIO_REQUERIDO
    tags:
              - despliegue

-   name:       Asegurar que el servidor web queda arrancado
    service:
        name:   nginx
        state:  started
    register:   arranque
    tags:
              - despliegue
