-   name:               Quiero NGINX Arriba !!!!!
    hosts:              localhost
    gather_facts:       false
    
    vars:
        nginx:
            version:    1.15
        web:
            repo:       https://github.com/IvanciniGT/webEjemploAnsible
            puerto:     8080
            carpeta:    /home/ubuntu/environment/datos/web

    pre_tasks:
    
        -   name:       Obtener el SO de la máquina sobre la que trabajo
                        # Y ese dato... que lo sacaré con algún módulo (SETUP)
            register:   sistema_operativo
            tags:
                      - always  # Este es un tag especial de ANSIBLE
            
        -   name:       Asegurar que estamos en un entorno ubuntu
                        # Detengo el PLAY para el host
            when:       # si la máquina NO ES UBUNTU [sistema_operativo]
            tags:
                      - always  # Este es un tag especial de ANSIBLE
        
        -   name:       Asegurar que git queda instalado en el entorno
                        # Si no esté git... pues ya sabes FELIPE !
            tags:
                      - despliegue

    tasks:
    
        -   name:       Asegurar que NGINX queda instalado en el entorno
                        # Si no lo está... pues ya sabes FELIPE !
                        # [nginx.version]
            tags:     
                      - instalacion
                      
        -   name:       Asegurar que NGINX queda configurado como necesito para mi web
                        # Si no lo está... pues ya sabes FELIPE !
                        # [nginx.puerto , nginx.carpeta]
            notify:     REINICIO_REQUERIDO
            tags:     
                      - configuracion
    
    post_tasks:
    
    
    handlers:
    
        -   name:       Asegurar que nginx queda reiniciado
                        # Reinicia nginx... por el articulo 33
            listen:
                      - REINICIO_REQUERIDO
